### ISSUE TITLE
Patching LVDS for Arch Linux ARM

### ISSUE THREAD

**Issue by gondorf** [UDOOboard/uboot-imx#2]
I've been planning on patching the LVDS functionality into Arch Linux ARM with the udoo quad (so I can use the 15" non-touch Innolux panel) and have a few noob questions. I've looked here at your source uboot and there doesn't appear to be anything regarding LVDS for the quad...

Also, will I need to patch the kernel as well or only the uboot?

**Comment by ektor5** [comment]
Hi Gordorf,

What you have to do is easy and doesn't involve uboot.

Download the kernel sources
Compile against imx6q-udoo-lvds7.dtb (or 15)
Load the dtb in uboot stage
Have fun ;)

Ek5

PS.: for 15 you have to use video cmdargs like in previous kernel version
(3.0.35)
Look at online docs at udoo.org

**Comment by gondorf** [comment]
@ektor5 

Hey, I finally got the chance to try this out. I did as you said...
1. Downloaded the kernel sources
2. Added the file imx6q-udoo-15lvds.dts into the sources (and updated Makefile accordingly)
3. Did a makepkg to build the Linux kernel for Arch ARM (and pacman installed the new kernel)
4. Successfully loaded the imx6q-udoo-15lvds.dtb in the uboot stage (switched out with imx6q-udoo.dtb in the env variables)
5. Followed the udoo docs and did the cmdargs:

```
setenv mmcargs setenv bootargs console=${console},${baudrate} root=${mmcroot} ${hdmi_patch} fbmem=24M video=mxcfb0:dev=ldb,1366x768M@60,if=RGB­24,bpp=32
```

(and I tried these cmdargs too...)

```
setenv mmcargs setenv bootargs console=${console},${baudrate} root=${mmcroot} ${hdmi_patch} fbmem=24M video=mxcfb0:dev=ldb,LDB-WXGA,if=RGB24,bpp=32
```

However, it's not working. It boots to the login (through serial)...and I get a backlight, but there is nothing on the screen. 

Do I need a different command because I'm using the Arch Linux ARM uboot maybe? Let me know if I missed any glaringly obvious steps...

**Comment by gondorf** [comment]
@ektor5

...and this line may be useful? (it's some of the output that spits out when the kernel is starting)

```
[    8.712531] imx-ldb 2000000.aips-bus:ldb@020e0008: could not determine data mapping: -22      
[    8.712557] imx-drm display-subsystem: failed to bind 2000000.aips-bus:ldb@020e0008 (ops imx_l
db_ops [imx_ldb]): -22                                                                         
[    8.713380] imx-drm display-subsystem: master bind failed: -22    
```

**Comment by ektor5** [comment]
Good job!
Mmmh... It's all correct, but the thing I don't get is "Added the file
imx6q-udoo-15lvds.dts into the sources".

Are you using our 3.14.28 kernel (http://github.com/UDOOboard/linux_kernel),
which is tested, or the mainline one?

Ek5

**Comment by gondorf** [comment]
I was trying to use the mainline kernel. Would it be better to use that old kernel with Arch Linux ARM? I tried compiling some earlier kernels but had issues with gcc...

**Comment by patrykk** [comment]
Related to GCC please use path from this issue: https://github.com/UDOOboard/linux_kernel/issues/4
