### ISSUE TITLE
PLAIN_VERSION undeclared

### ISSUE THREAD

**Issue by jgeslin** [UDOOboard/uboot-imx#6]
Hi,

Building u-boot following the provide guidelines:

> ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- make udoo_neo_config
> ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- make

I get the following error:
`tools/mkenvimage.c: In function ‘main’:`
`tools/mkenvimage.c:120:35: error: ‘PLAIN_VERSION’ undeclared (first use in this function)`
`printf("%s version %s\n", prg, PLAIN_VERSION);`

I can't figure out from where it come neither how to fix it.

Is anybody able to help here ?

Regards,
Jeremy.

**Comment by vpeter4** [comment]
Try

```
ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- make mrproper
ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- make udoo_neo_config
ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- make
```

**Comment by jgeslin** [comment]
This did not help, unfortunately.

**Comment by vpeter4** [comment]
Did you use correct branch (2015.04.imx-neo)?
Because here I don't have any problem.

**Comment by jgeslin** [comment]
Yes I am.
This looks like an environment problem. Indeed the PLAIN_VERSION is properly declared in "include/generated/version_autogenerated.h" which is included from "include/version.h". If I force this version.h inclusion (#include "../include/version.h") in mkenvimage.c it pass, but fails with the same error on further .c file including <version.h>.
It seems another version.h file is included instead ... but which one ?

**Comment by fmntf** [comment]
Which version of GCC are you using?

**Comment by jgeslin** [comment]
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 4.8.4-2ubuntu1~14.04.1' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/arm-linux-gnueabihf/include/c++/4.8.4 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --disable-libitm --disable-libquadmath --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-armhf-cross/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-armhf-cross --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-armhf-cross --with-arch-directory=arm --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libgcj --enable-objc-gc --enable-multiarch --enable-multilib --disable-sjlj-exceptions --with-arch=armv7-a --with-fpu=vfpv3-d16 --with-float=hard --with-mode=thumb --disable-werror --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=arm-linux-gnueabihf --program-prefix=arm-linux-gnueabihf- --includedir=/usr/arm-linux-gnueabihf/include
Thread model: posix
gcc version 4.8.4 (Ubuntu/Linaro 4.8.4-2ubuntu1~14.04.1)

**Comment by jgeslin** [comment]
And same result using "gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611)".

**Comment by fmntf** [comment]
We can build u-boot with Ubuntu 14.04 and 16.04 (with the default cross-compiler, `gcc-arm-linux-gnueabihf`). It is something related to your environment. Could you try on a clean Ubuntu VM?

**Comment by jgeslin** [comment]
I tried on a clean 14.04.1 Ubuntu server and it passes.
Still don't know the root cause but at least I can continue from there !

**Comment by EdSwarthout** [comment]
Just to followup, I hit the same issue and found it is due a version.h in /usr/local/include.
Removing it fixed the issue.  See: https://lists.denx.de/pipermail/u-boot/2018-May/330090.html
